### ISSUE TITLE
postgres backup Bitwarden Unified beta database

### ISSUE THREAD

**Issue by seanob86** [ttionya/vaultwarden-backup#114]
I know the official bitwarden unified beta is out of scope of this project: https://bitwarden.com/help/install-and-deploy-unified-beta/

However will the postgres backup of this project in theory will work with the bitwarden unified project using postgres as db backend?

**Comment by ttionya** [comment]
This project only provides backup support for the unofficial [Vaultwarden](https://github.com/dani-garcia/vaultwarden) and has not been tested with the official Bitwarden.

PS: In theory, backing up only the database should be universal. However, please note that any pull requests and issues related to non-Vaultwarden backups will not receive support (comments excluded).

**Comment by seanob86** [comment]
Understood and what I expected.
