### ISSUE TITLE
Custom zip name

### ISSUE THREAD

**Issue by mr-n0cturne** [ttionya/vaultwarden-backup#121]
Hello.

could you please make the zip filename customizable.
Current pattern: BACKUP_FILE_ZIP="${BACKUP_DIR}/**_backup._**${NOW}.${ZIP_TYPE}"
Desired pattern: BACKUP_FILE_ZIP="${BACKUP_DIR}/**_${ZIP_NAME}_**${NOW}.${ZIP_TYPE}"

Thank you!

**Comment by ttionya** [comment]
I haven't encountered a scenario where I need to modify file names. Could you please share the specific context in which you encountered this?
