### ISSUE TITLE
I have some warnings in the log and I don't understand how to fix them

### ISSUE THREAD

**Issue by alatouz** [ttionya/vaultwarden-backup#124]
here is my setup
`      - MAIL_SMTP_ENABLE=TRUE
      - MAIL_SMTP_VARIABLES=-S smtp-use-starttls -S smtp=smtp://smtp.free.fr:587 -S smtp-auth=login -S smtp-auth-user=xxx.xxx -S smtp-auth-password=passxxx -S from=xxx.xxx@free.fr
      - MAIL_TO=xxx.xxx@free.fr
      - MAIL_WHEN_SUCCESS='TRUE'
      - MAIL_WHEN_FAILURE='TRUE'`
  
here are the error messages
```
mail: Warning: variable superseded or obsoleted: smtp
mail: Warning: variable superseded or obsoleted: smtp-auth-user
mail: Warning: variable superseded or obsoleted: smtp-auth-password
mail: Obsoletion warning: please do not use *smtp*, instead assign a smtp:// URL to *mta*!
mail: Obsoletion warning: Use of old-style credentials, which will vanish in v15!
mail:   Please read the manual section "On URL syntax and credential lookup"
mail send was successfully
```
THANKS

**Comment by ttionya** [comment]
Starting from v1.19.0, we are using `s-nail` instead of `heirloom-mailx`. `s-nail` is warning users to switch to their new MTA credential verification method. For more detailed information, please refer to the #117 .
