### ISSUE TITLE
Command Not Found When Using .env File With Multiple Remote Destinations

### ISSUE THREAD

**Issue by Fiestaman** [ttionya/vaultwarden-backup#126]
When I add a second remote destination to my .env file, I get the following errors in the container logs and the second remote destination is not utilized. Backing up to original remote continues as normal.
>/dev/fd/63: line 3: RCLONE_REMOTE_NAME_1:: command not found
/dev/fd/63: line 4: RCLONE_REMOTE_DIR_1:: command not found

Here are the entries in the .env file:
>RCLONE_REMOTE_NAME="VaultwardenBackup"
>RCLONE_REMOTE_DIR="/bucketname/VaultwardenBackup/"
>RCLONE_REMOTE_NAME_1: "storjVaultwardenBackup"
>RCLONE_REMOTE_DIR_1: "/bucketname/backup/"

However, I tried starting the container using -e flags while removing the two entries from the .env file and I did not get these errors. Second remote location loaded correctly and data was backed up to both locations.
`-e RCLONE_REMOTE_NAME_1=storjVaultwardenBackup -e RCLONE_REMOTE_DIR_1="/bucketname/backup/"`

**Comment by ttionya** [comment]
> RCLONE_REMOTE_NAME_1: "storjVaultwardenBackup"
> RCLONE_REMOTE_DIR_1: "/bucketname/backup/"

In your env file, kindly employ the use of the equals sign (`=`).
