### ISSUE TITLE
请问一些关于备份到本地的问题

### ISSUE THREAD

**Issue by asasdsaweasd** [ttionya/vaultwarden-backup#156]
请问本项目是只支持rclone备份到云端吗，我现在想先备份到本地再备份到云端的需求
因为我的vaultwarden是用dokcer安装在了固态硬盘上，想先备份到另一块机械硬盘上(一般情况下机械硬盘坏的概率比固态低)
如果只能云端的话，使用cron直接cp运行中的vaultwarden会有问题吗

**Comment by ttionya** [comment]
Rclone 支持使用 `local` 备份到本地文件系统，如果你希望同时备份到多个存储，可以参考 https://github.com/ttionya/vaultwarden-backup/blob/master/docs/multiple-remote-destinations.md。
