### ISSUE TITLE
Suggestion: lvm snapshot instead of sqlite .backup

### ISSUE THREAD

**Issue by nuuantoine** [ttionya/vaultwarden-backup#159]
I will try to implement it and will eventually post my solution for it, but Vaultwarden can now store organization event and backup of vaultwarden can take a huge amount of time because our sqlite db is 14GB for only 90 days of events.
It would be very nice to have a way to :  

- stop vaultwarden
- do a lvm snapshot
- start vaultwarden again
- copy the sqllite file instead of using sqlite command.
- finish backup. 

What do you think about it ?

**Comment by ttionya** [comment]
I don't have extensive knowledge of LVM, but after researching, I found that to create an LVM snapshot, the files need to be on a LV (logical volume).

It means the vaultwarden data folder itself needs to be on a LV. However, vaultwarden does not require storing data on an LV. For users, placing data on a LV is an unnecessary operation. Additionally, this tool runs in a container and cannot start or stop another container.

In summary, using LVM snapshots would require users to migrate their data, introducing a breaking change, which this tool aims to avoid. Secondly, the backup process does not assume users need to stop their services. Thirdly, a container should not control the running state of another container (and perhaps it can't). Therefore, there are no plans to support LVM snapshot backups at this time.

Of course, if I have any misunderstandings about LVM, please correct me.
