### ISSUE TITLE
Does this support backing up passkeys?

### ISSUE THREAD

**Issue by kainjinez** [ttionya/vaultwarden-backup#168]
I'm using your solution to back up my vaultwarden.
I'm not sure If we are supporting backing up the passkeys. I did not find any information in the repository, so I place a question here.
Thanks.

**Comment by ttionya** [comment]
What is a passkey? Perhaps it is not part of the service data. You can check [here](https://github.com/dani-garcia/vaultwarden/wiki/Backing-up-your-vault) to understand the official recommendations on what needs to be backed up.
