### ISSUE TITLE
Backup source

### ISSUE THREAD

**Issue by Nightwalker83** [ttionya/vaultwarden-backup#170]
Hi,

Is the backup source
`
docker run --rm -it \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  ttionya/vaultwarden-backup:latest \
  rclone config show
`
the folder where the config file is stored?

Thanks,

Aaron

**Comment by ttionya** [comment]
Are you asking about the configuration `--mount type=volume,source=vaultwarden-rclone-data,target=/config`? This is Docker syntax, equivalent to `-v vaultwarden-rclone-data:/config`.

**Comment by Nightwalker83** [comment]
Yes, I have the vaultwarden-rclone directory in the volumes directory and not sure were I need to put the .env because form memory it only says /.env on the files page on this github.

**Comment by ttionya** [comment]
```bash
docker run --rm -it \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  --mount type=bind,source=/path/to/your/envfile,target=/.env \
  ttionya/vaultwarden-backup:latest
```

**Comment by Nightwalker83** [comment]
Ah ok! Thanks.
