### ISSUE TITLE
FR: 支持企业微信群机器人推送

### ISSUE THREAD

**Issue by fangyuan99** [ttionya/vaultwarden-backup#171]
文档： https://developer.work.weixin.qq.com/document/path/91770
使用非常简单，记住key之后webhook推送

**Comment by ttionya** [comment]
This tool does not support specific notification methods, but we provide more general notification methods, which you can refer to in the [documentation](https://github.com/ttionya/vaultwarden-backup#ping). Additionally, we recommend using tools like [healthcheck](https://healthchecks.io/), so you can be promptly notified if a successful backup notification is not received.

本工具不会支持特定的通知方式，但我们提供了更通用的通知方式，可以参考[文档](https://github.com/ttionya/vaultwarden-backup#ping)。另外，我们更建议使用类似 [healthcheck](https://healthchecks.io/) 的工具，这样在未接收到成功备份的通知时可以及时通知你。
