### ISSUE TITLE
备份通知到 Telegram bot 时，ping_url 和 ping_url_curl_options 应该如何填写？

### ISSUE THREAD

**Issue by leic4u** [ttionya/vaultwarden-backup#176]
我的例子：

```
    # PING_URL: ''
    # PING_URL_CURL_OPTIONS: ''
    # PING_URL_WHEN_START: ''
    # PING_URL_WHEN_START_CURL_OPTIONS: ''
      PING_URL_WHEN_SUCCESS: 'https://api.telegram.com/bot123456789:AABBCC112233ddeeff445566/sendmessage'
      PING_URL_WHEN_SUCCESS_CURL_OPTIONS: '-H "Content-Type: application/json" -d "{\"chat_id\": \"123456789\", \"text\": \"Vaultwarden 备份成功！\n- 备份应用：https://vaultwarden.abc.com/\n- 坚果云备份成功！\n- %{subject}\n- %{content}\", \"parse_mode\": \"Markdown\"}" -X POST'
      PING_URL_WHEN_FAILURE: 'https://api.telegram.com/bot123456789:AABBCC112233ddeeff445566/sendmessage'
      PING_URL_WHEN_FAILURE_CURL_OPTIONS: '-H "Content-Type: application/json" -d "{\"chat_id\": \"123456789\", \"text\": \"Vaultwarden 备份失败！\n- 备份应用：https://vaultwarden.abc.com/\n- 有网盘备份失败，请检查备份日志！\n- %{subject}\n- %{content}\", \"parse_mode\": \"Markdown\"}" -X POST'
```

其中：
1. `api.telegram.com`：如果机器在墙内，可以换成反代地址，反代教程可以搜索`TG bot 通过 Cloudflare Workers 搭建反向代理服务`。
2. `\"chat_id\": \"123456789\"`：需要换成自己的`chat_id`，可通过私聊 @getuseridbot 获得。
3. `bot123456789:AABBCC112233ddeeff445566`：这个是 `bot token`，可通过 @botfather 创建一个新的 bot 获得。

**Comment by Saberafter** [comment]
感谢分享，个人测试配置时的一些摸索：  
1. `api.telegram.com` 这个地址如果收不到消息，可以试试 `api.telegram.org`  
2. 如果已经部署了本地代理，不想配置反代服务，可以在 `CURL_OPTIONS` 里加一条 `-x <你的代理地址>`，比如 `-x http://127.0.0.1:7890`  
3. 配置完 bot 可以先在外面试试基础的 curl 能不能通，方便排查 bot 配置和本地环境问题， `$token` 和 `$chat_id` 替换为你自己的：
```bash
curl -H "Content-Type: application/json" -d "{ \"chat_id\": \"$chat_id \", \"text\": \"测试消息\", \"parse_mode\": \"Markdown\" }" -X POST "https://api.telegram.org/bot$token/sendMessage"
```
4.  直接使用 [healthcheck.io](https://healthchecks.io/) 也很快，它可以周期内监控服务 down 情况，而且它自带 telegram 和邮箱等非常多的通知服务。不过我只需要一条所见即所得的推送，它对我有点大材小用（）

**Comment by leic4u** [comment]
> 感谢分享，个人测试配置时的一些摸索：
> 
>     1. `api.telegram.com` 这个地址如果收不到消息，可以试试 `api.telegram.org`
> 
>     2. 如果已经部署了本地代理，不想配置反代服务，可以在 `CURL_OPTIONS` 里加一条 `-x <你的代理地址>`，比如 `-x http://127.0.0.1:7890`
> 
>     3. 配置完 bot 可以先在外面试试基础的 curl 能不能通，方便排查 bot 配置和本地环境问题， `$token` 和 `$chat_id` 替换为你自己的：
> 
> 
> curl -H "Content-Type: application/json" -d "{ \"chat_id\": \"$chat_id \", \"text\": \"测试消息\", \"parse_mode\": \"Markdown\" }" -X POST "https://api.telegram.org/bot$token/sendMessage"
> 
>     4. 直接使用 [healthcheck.io](https://healthchecks.io/) 也很快，它可以周期内监控服务 down 情况，而且它自带 telegram 和邮箱等非常多的通知服务。不过我只需要一条所见即所得的推送，它对我有点大材小用（）

抱歉，是我分享里面填的 TG API 地址有问题，`telegram.com` 是一家报纸机构的域名，TG 的正确域名是 `telegram.org`，已更正。因为我都是使用反代地址的，可以无视代理环境，也就不用填 TG 自己的域名，所以没有发现这个问题。
