### ISSUE TITLE
Change the TIMEZONE environment variable to TZ

### ISSUE THREAD

**Issue by MilesTEG1** [ttionya/vaultwarden-backup#27]
Hello,
I'm starting to use you backup container for bitwardenRS.
And I've got a problem with the TIMEZONE environment variable.
It has to be set to utc, or I think utc+2 for me, in Europe/Paris.
But what will happened when the DST switch to utc+1 ? I would have to modify the TIMEZONE variable.
And next year, again...

So, I propose to change this TIMEZONE variable to the TZ variable, witch can be set to Europe/Paris, or another TZ database name.
Can this be done ?
Thank in advance.

**Comment by ttionya** [comment]
Hey @MilesTEG1 ,

Very happy that this project can help you.

The `TIMEZONE` environment variable is used as `tzdata`, as shown in the readme, you can see more details at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.

You can set `TIMEZONE` to `Europe/Paris` and the Linux system will automatically handle DST for you. For me, I just set it to `Asia/Hong_Kong` and it works fine.
