### ISSUE TITLE
How decrypt rclone config file？

### ISSUE THREAD

**Issue by ibeange** [ttionya/vaultwarden-backup#28]
I run it with docker-compose,but it's restarting,log shows this:
```
"Enter configuration password:
password:2021/05/02 19:51:13 Failed to read line: EOF
storage system connection failure"
```
how can I solve this problem?

**Comment by ttionya** [comment]
Hey @ibeange ,

Sorry it took so long to get back to you, I was away from my computer for the last few days.

It looks like you didn't configure rclone correctly. Did you set it up by [`rclone config`](https://github.com/ttionya/BitwardenRS-Backup#backup)?

**Comment by ibeange** [comment]
你好，我已经在其他地方咨询过你了，这里我再把我的情况详细说明一下：

我想使用docker在我的小服务器上自建一个bitwarden，目前是想使用docker-compose一次性部署，但是有一些关键信息我不想直接写在配置文件中，比如bitwarden的admin token，备份需要的Zip压缩包密码，还是有rclone config我也想加密，但是当我加密了rclone config之后部署就会出错，你这个项目不能在我的docker中启动，查看日志发现需要我输入密码，但是我知道应该在哪里输入。另外我注意到如果使用docker secret需要开启swarm，而整个部署方式也发生了变化，不再使用docker-compose，而是直接使用docker stack，我是docker的初学者，不知道该如何操作能更好的部署我想要的环境，不知道你能不能给我一点指导，非常感谢！

以下是我的docker-compose的yaml文件

```version: '3.8'

services:

    bitwarden:
        image: bitwardenrs/server:latest
        container_name: bitwarden
        restart: on-failure
        ports: 
            - ${BITPORT}:80
            - 3012:3012
        volumes:
            - ${BITWARDEN_DATA}:/data/
        environment:
            - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
            - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
            - DOMAIN=${DOMAIN}
            - ADMIN_TOKEN=${ADMIN_TOKEN}
            - LOG_FILE=${LOG_FILE}
            - LOG_LEVEL=${LOG_LEVEL}
            - EXTENDED_LOGGING=${EXTENDED_LOGGING} 
            - TZ=${DEFAULT_TIMEZONE}

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log:/var/log/nginx/
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
            - ${WEB_ROOT_PATH}:/var/www
        environment:
            - TZ=${DEFAULT_TIMEZONE}  

    bw-backup:
        image: ttionya/bitwardenrs-backup:latest
        container_name: bw-backup
        restart: always
        network_mode: host
        environment:
            - RCLONE_REMOTE_NAME=${RCLONE_REMOTE_NAME}
            - RCLONE_REMOTE_DIR=${RCLONE_REMOTE_DIR}
            - CRON=${CRON}
            - ZIP_ENABLE=${ZIP_ENABLE}
            - ZIP_PASSWORD=${ZIP_PASSWORD}
            - ZIP_TYPE=${ZIP_TYPE}
            - BACKUP_FILE_DATE_SUFFIX=${BACKUP_FILE_DATE_SUFFIX}
            - BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS}
            - MAIL_SMTP_ENABLE=${MAIL_SMTP_ENABLE}
            - MAIL_SMTP_VARIABLES=${MAIL_SMTP_VARIABLES}
            - MAIL_TO=${MAIL_TO}
            - MAIL_WHEN_SUCCESS=${MAIL_WHEN_SUCCESS}
            - MAIL_WHEN_FAILURE=${MAIL_WHEN_FAILURE}
            - TZ=${DEFAULT_TIMEZONE}
        volumes:
            - ${BITWARDEN_DATA}:/bitwarden/data/
            - ${BITWARDEN_RCLONE_CONFIG}:/config/rclone

    fail2ban:
        image: crazymax/fail2ban:latest
        container_name: fail2ban
        restart: always
        network_mode: host
        privileged: true
        environment:
            - F2B_LOG_TARGET=${F2B_LOG_TARGET}
            - F2B_LOG_LEVEL=${F2B_LOG_LEVEL}
            - F2B_DB_PURGE_AGE=${F2B_DB_PURGE_AGE}
            - SSMTP_HOST=${SSMTP_HOST}
            - SSMTP_PORT=${SSMTP_PORT}
            - SSMTP_HOSTNAME=${SSMTP_HOSTNAME}
            - SSMTP_USER=${SSMTP_USER}
            - SSMTP_PASSWORD=${SSMTP_PASSWORD}
            - SSMTP_TLS=${SSMTP_TLS}
            - TZ=${DEFAULT_TIMEZONE}
        cap_add:
            - NET_ADMIN
            - NET_RAW
        volumes:
            - ${FAIL2BAN_DATA}:/data
            - ${BITWARDEN_DATA}:/var/log:ro
```

而在使用你这个项目时，如果没有配置文件会要求创建一个新的配置文件，这里就有看到可以Set configuration password

```
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
```

而我设置了密码之后，使用这么docker container会不能启动，查看日志是要我输入密码
我该如何去写这个yaml文件才能既保证安全性又能成功使用stack deploy？
非常感谢！

**Comment by ttionya** [comment]
你好 @ibeange ，

vaultwarden 不支持配置文件加密，你可以查看它的[文档](https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview)，或许你可以不开启 admin 管理。但你的 STMP 等配置确实没办法隐藏。

现在 vaultwarden-backup 不支持加密 Rclone remote 配置，所以现在不要对它加密，后面我会看看好不好支持。因为就算支持其实也就是加一个环境变量，要保证这个环境变量的安全性你就得使用 Docker Secrets。不过就算支持也不会是这几天的事，因为没搞过，我得写了测，所以你要用就必须先不加密了。

然后你想使用 Docker Secrets 保证部分敏感字段的安全性，你确实可以使用 docker swarm，它可以使用 docker-compse.yml 部署，详细文档可以看[这里](https://docs.docker.com/engine/swarm/stack-deploy/#deploy-the-stack-to-the-swarm)，`docker stack deploy --compose-file docker-compose.yml stackdemo`。

在添加 Docker Secrets 后，你可以在 [Docker Secrets](https://github.com/ttionya/vaultwarden-backup/blob/master/README_zh.md#docker-secrets) 看到配置方法。

我其实也没使用过 docker swarm，所以还真没法给你什么很有价值的建议。现在你卡在 Rclone 配置加密上，你先不加密，把程序跑起来，再一点一点去改会比较好。

**Comment by ttionya** [comment]
@ibeange ，

我查询了 Rclone 的文档，发现可以通过设置 `RCLONE_CONFIG_PASS` 环境变量指定配置文件的密码，你可以尝试一下，文档在[这](https://rclone.org/docs/#configuration-encryption)。

**Comment by ibeange** [comment]
明天晚上试试！非常感谢！
