### ISSUE TITLE
send-mail: applet not found

### ISSUE THREAD

**Issue by Yanik39** [ttionya/vaultwarden-backup#36]
Hello,

When i enter the container (docker exec -it Bitwarden_Backup /bin/bash) and run following commands. I get email.
```
cd ..
source .env
echo "hi" | mailx -v -s "hello" $MAIL_SMTP_VARIABLES $MAIL_TO
```

But with regular container run i get;

```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2021-11-14 19:35:01 ....A         3072       116304  attachments.20211114_193501.tar
2021-11-14 19:35:01 ....A         1658               config.20211114_193501.json
2021-11-14 19:35:01 ....A       413696               db.20211114_193501.sqlite3
2021-11-14 19:35:01 ....A         4608               rsakey.20211114_193501.tar
------------------- ----- ------------ ------------  ------------------------
2021-11-14 19:35:01             423034       116304  4 files

upload backup file to storage system
delete 90 days ago backup files
send-mail: applet not found
mail sending failed
```

Not sure how to debug it. Looking for some help.
Thanks

**Comment by ttionya** [comment]
@Yanik39 ,

I'm very sorry for taking so long to reply to you, I don't use my computer for some reasons these days.

I have no experience in dealing with MTA, so I searched the internet for articles about it, but unfortunately there is nothing I want.

I am using zoho SMTP to send emails and it is working fine. I would like to know your host system type and mail provider to try to reproduce the issue.

Maybe we can use other notification methods. You can use `PING_URL` with [healthcheck.io](https://healthchecks.io/) and it will only alert you when it doesn't receive a ping.

**Comment by Yanik39** [comment]
`
Resolving host smtp.mailbox.org . . . done.
Connecting to 80.241.60.196:465 . . . connected.
Comparing DNS name: "*.mailbox.org"
220 smtp1.mailbox.org ESMTP Postfix
>>> HELO backup.example.com
250 smtp1.mailbox.org
>>> MAIL FROM:<root@backup.example.com>
250 2.1.0 Ok
>>> RCPT TO:<notifications@example.com>
554 5.7.1 <unknown[$IP]:5787>: Client host rejected: Access denied
smtp-server: 554 5.7.1 <unknown[$IP]:5787>: Client host rejected: Access denied
"/root/dead.letter" 11/392
. . . message not sent.
mail sending failed`

Hello again,

My env file has "from" adress. And it works when i use it manually. But somehow with container i get above error which is app uses my docker hostname.
My Docker hostname: backup.example.com
My Env file from adress: info@example.com

App doesnt use env file from adress, somehow overwrites with hostname: root@backup.example.com. So access is denied by smtp server. But everything works when i send email manually like at my first post.

Any idea why?
