### ISSUE TITLE
How about to expose port rclone token port in Docker?

### ISSUE THREAD

**Issue by 0x7a7a** [ttionya/vaultwarden-backup#37]
Hello,
  I configured it according to the document yesterday. I found that in ```rclone config```, i need to click ```http://127.0.0.1:53682/auth?state=xxxx``` to get the token (I use 'onedrive'). But I set it on my remote server, so there is no way to request this url (cannot use -P for port mapping).
Finally, I used the ```rclone config``` command directly on the server to get the ```rclone.conf``` file, and then copied it to volume (vaultwarden-rclone-data) to solve.
So should it be Exposed  in DockerFile?

---

你好,
我昨天在自己的远程服务器上根据文档运行了备份服务,在执行docker中的```rclone config```命令时候遇到了问题.在获取token时候需要点击一个```http://127.0.0.1:53682/auth...```的地址来获取onedrive的token,但是因为在镜像中没有暴露出这个端口,所以无法用-P命令做端口映射暴露给宿主机.
最后我通过服务器直接执行```rclone config```(rclone二进制,非docker版本)来获得这个rclone.conf文件,然后复制到了```volume```的本地目录中才使得docker能够使用rclone.
我想问下,是否需要在DockerFile中暴露这类端口来解决这个问题(可能不止53682这个端口)?

**Comment by ttionya** [comment]
Hey @0x7a7a ,

You are using a wrong way to configure rclone.

The correct way is to execute `rclone config` on the local machine to get the *token*, then execute the `docker run --rm -it --mount type=volume,source=vaultwarden-rclone-data,target=/config/ ttionya/vaultwarden-backup:latest rclone config` command on the server to import the *token*. (Use auto config? select N)

**Comment by 0x7a7a** [comment]
@ttionya 
Thank you very much for your reply.  
I am really just learning to use rclone,I didn't read the whole rclone document. 
Although I have solved the problem, I will follow your prompt next time. I think that's the right thing to do.
Thank you again for your work.
