### ISSUE TITLE
MAIL_SMTP_VARIABLES are not working with .env File

### ISSUE THREAD

**Issue by meiomei** [ttionya/vaultwarden-backup#38]
When using .env file with included MAIL_SMTP_VARIABLES mail sending is not working. Error is "send-mail: applet not found". I think the problem occurs because get_env MAIL_SMTP_VARIABLES is not called in init_env. After adding this line manually everything seems to work. Can you please add this line?

**Comment by ttionya** [comment]
@meiomei ,

Thank you very much for your issue, a month ago @Yanik39 opened a similar issue #36  and I tried to fix it but had no idea. Now I can finally get it fixed.
