### ISSUE TITLE
Change /bitwarden/data/ to /data/

### ISSUE THREAD

**Issue by quyleanh** [ttionya/vaultwarden-backup#40]
As I can see, the docker-compose file is outdated and need to be updated.
Like this one:
https://github.com/ttionya/vaultwarden-backup/blob/a52669e6fc22bda118b83b147c506f26802c3022/docker-compose.yml#L36

Could you update it? Thank you.

**Comment by ttionya** [comment]
@quyleanh ,

What needs to be updated? I don't understand what you mean, please provide details.

**Comment by quyleanh** [comment]
@ttionya I haven't checked yet, but I think it should be `vaultwarden-data:/data/ `.
If there is no problem with these code, so I will close this issue.

**Comment by ttionya** [comment]
Hey @quyleanh ,

It has no problems. The data directory is mapped to the `/bitwarden/data/` directory, which the tool will use.

However, mapping to the `/bitwarden/data/` directory was a mistake in early development. I think using `/data/` is a better choice, people using [Automatic Backups](https://github.com/ttionya/vaultwarden-backup#automatic-backups) don't need to specify `-e DATA_DIR="/data"` anymore. But changing it is a **BREAK CHANGE**, which is not a good idea, **I won't change it**.

**Comment by quyleanh** [comment]
@ttionya thank you for your explanation.
I will try to use docker-compose.yml file then report if is there any problem.
This issue is closed.
