### ISSUE TITLE
Replace existent backup file with new one

### ISSUE THREAD

**Issue by quyleanh** [ttionya/vaultwarden-backup#42]
When I do backup every 5 minutes, I notice that the backup file never updated as my config.
It's seems that 7z tool cannot overwrite existent files. Could you update the backup script to delete the old one before compressing and uploading the new one?

Thank you.

**Comment by ttionya** [comment]
Hey @quyleanh ,

The backup tool re-creates the directory each time it is run via cron, and it is used to store the files that need to be uploaded to remote storage. So there will not be a situation where the 7z tool generates a zip archive that needs to overwrite the original files.

Maybe you mean that rclone does not overwrite existing files when uploading to remote storage? If so, I hope you will provide the type of remote storage used.

**Comment by quyleanh** [comment]
Thank you for your quick response. Currently I use onedrive as remote storage. I am not sure if `rclone copy` command replace the old backup or not.

**Comment by quyleanh** [comment]
My bad. It did uploaded the new one. I just check the modified time on detail panel. There is no problem with backup code.

![Screenshot_20220109-142715_OneDrive](https://user-images.githubusercontent.com/9365035/148673328-f96fbc4d-e68b-4aed-8a0b-d3941b8f84b4.png)

I will close this issue.

**Comment by ttionya** [comment]
I use OneDrive as remote storage too.

You can find historical versions of each file, so you can use days(`%Y%m%d`) as filenames without losing any versions of files that are backed up every day. This is useful.
