### ISSUE TITLE
Wrong From Adress

### ISSUE THREAD

**Issue by Yanik39** [ttionya/vaultwarden-backup#43]
Part 2 of #36 
```
Resolving host smtp.mailbox.org . . . done.
Connecting to 80.241.60.196:465 . . . connected.
Comparing DNS name: "*.mailbox.org"
220 smtp1.mailbox.org ESMTP Postfix
>>> HELO backup.example.com
250 smtp1.mailbox.org
>>> MAIL FROM:<root@backup.example.com>
250 2.1.0 Ok
>>> RCPT TO:<notifications@example.com>
554 5.7.1 <unknown[$IP]:5787>: Client host rejected: Access denied
smtp-server: 554 5.7.1 <unknown[$IP]:5787>: Client host rejected: Access denied
"/root/dead.letter" 11/392
. . . message not sent.
mail sending failed
```

Hello again,

My env file has "from" adress. And it works when i use it manually. But somehow with container i get above error which is app uses my docker hostname.
My Docker hostname: backup.example.com
My Env file from adress: info@example.com

App doesnt use env file from adress, somehow overwrites with hostname: root@backup.example.com. So access is denied by smtp server. But everything works when i send email manually like at my #36 post.

Any idea why?

**Comment by ttionya** [comment]
hey @Yanik39 ,

I'm sorry to hear that you are still having trouble with sending emails. The previous error "send-mail: applet not found" has been fixed.

I checked the `from` and `sender` sections of the [mailx documentation](https://www.systutorials.com/docs/linux/man/1-heirloom-mailx/). mailx looks like it sets the `from` field to machine's hostname, try changing your docker container hostname to make sure it is not valid at the Internet. Or see if the `sender` field solves the problem.
