### ISSUE TITLE
I'm completely lost but need a backup for Vaultwarden

### ISSUE THREAD

**Issue by queen4me** [ttionya/vaultwarden-backup#48]
Hello,

first of all thanks a lot for your tool which seems to be intended for a audience with better it-knowledge than I have.

I'm running Vaultwarden in a docker container on my mini-server with ubuntu 20.04 LTS.
If I understand you readme correct first of all I have to install and configure rclone. Which is the easiest way to do this on the Linux host using Microsoft OneDrive as cloud-storage?

The next step after succesfull installation/configuration of rclone would be to start docker-compose.yml for your tool and configure the environment variables and that's all there is to do?

After setting this up and running your container a backup is made every hour?
How exactly does rclone on the host interact with your container? This is something I don't understand.

**Comment by ttionya** [comment]
> If I understand you readme correct first of all I have to install and configure rclone.

Yes, Rclone just needs to be configured, you need to get the <token> on your computer and then enter the <token> into the server. See Rclone's documentation for more information.

> Which is the easiest way to do this on the Linux host using Microsoft OneDrive as cloud-storage?

Using Rclone is the easiest way I know of to use cloud storage.

> The next step after succesfull installation/configuration of rclone would be to start docker-compose.yml for your tool and configure the environment variables and that's all there is to do?

You can use the docker image without setting environment variables, but environment variables allow you to implement more features. After you finish configuring environment variables, start the container and that's all. Of course you can set some configurations for vaultwarden, you can read the [WIKI](https://github.com/dani-garcia/vaultwarden/wiki) for vaultwarden.

> After setting this up and running your container a backup is made every hour?

How often to backup is configured by `CRON`, and there are also instructions for `crond` configuration in the documentation.

> How exactly does rclone on the host interact with your container?

The backup tool is built on the rclone image (Dockerfile), so it includes the `rclone` command. It just uses the Rclone API to upload backup files to remote storage.

**Comment by queen4me** [comment]
Thanks a lot for your answer ttionya.

How does rclone inside your container make use of the config/setup I have to configure on the host system?

**Comment by ttionya** [comment]
https://rclone.org/remote_setup/#configuring-using-rclone-authorize

**Comment by queen4me** [comment]
I finally managed to configure rclone in your docker image.
How often and when will vaultwarden be backed up?

**Comment by ttionya** [comment]
Please read the [Environment Variables](https://github.com/ttionya/vaultwarden-backup#environment-variables) carefully.

**Comment by queen4me** [comment]
Works like a charm now!
Thanks a lot for helping.
