### ISSUE TITLE
Environment variable for passing rclone global flags or custom certificates

### ISSUE THREAD

**Issue by PhilippTreupel** [ttionya/vaultwarden-backup#49]
Hi @ttionya, 
my rclone remote is an FTP server in a closed network which does not use a certificate of a public ca. Therefore all rclone commands with this remote are failing unless you set the [global flag](https://rclone.org/flags/) ```--ftp-no-check-certificate```.
Since the network is closed and I trust my FTP server this is not an issue for me. But with vaultwarden-backup it is currently not possible to pass any of the [rclone global flags](https://rclone.org/flags/) to the scripts. 
Could you please add this option in form of an environment variable?
Another solution would be to trust the certificate of the FTP server which is easily done for the host on which the container is running, but not for the container itself. It has to be part of the container build according to this [post](https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image). Could you please add the ```update-ca-certificates``` command to the docker file? Then I could pass the custom certificate as a volume mapped to the ```/usr/local/share/ca-certificates/``` path in the container if I understood this correctly. 
What do you think? 
Is it possible to implement both options?

**Comment by ttionya** [comment]
@PhilippTreupel ,

I will support passing the Rclone global flags to the scripts.

Also, the `update-ca-certificates` command is already present in the image.
