### ISSUE TITLE
cannot access data directory

### ISSUE THREAD

**Issue by emilevandeven** [ttionya/vaultwarden-backup#50]
I used the following statement to create a backup container:
docker run -d \
  --restart=always \
  --name vaultwarden_backup \
  --volumes-from=vaultwarden \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  -e RCLONE_REMOTE_NAME="qnap" \
  -e DATA_DIR="/vw-data" \
  ttionya/vaultwarden-backup:latest

I installed rclone first and created a qnap config to backup to my qnap NAS. My data from Vaultwarden is in the map /vw-data, so no subdirectory. When the backup container runs it says "cannot access /vw-data: No such directory". What am I doing wrong?

**Comment by ttionya** [comment]
@emilevandeven ,

I'm guessing you just mapped the local `/vw-data` directory to the `/data` directory in the container, so you can just use `/data` according to the documentation.

**Comment by emilevandeven** [comment]
@ttionya Thanks! Now that problem doesn't exist anymore... but the next problem is facing up: rclone configuration not found. The rclone.conf is in my home dir, but I copied it to "/var/lib/docker/volumes/vaultwarden-rclone-data/_data" as well (I see in the volumes that vaultwarden-rclone-data is mounted to that dir). Still not found. Should there be a dir /config/ anywhere?

**Comment by ttionya** [comment]
@emilevandeven , I didn't try copying the config file to the volume, you could try removing the backup container and restarting it (I'm not sure it works).

The correct way to do this is to execute the `... rclone config` command according to the documentation, on the server, you can paste the token to generate the Rclone config file.

**Comment by emilevandeven** [comment]
Thanks for the help! It works now
