### ISSUE TITLE
关于Rclone在docker中运行

### ISSUE THREAD

**Issue by L1cardo** [ttionya/vaultwarden-backup#51]
你说要提前配置好rclone，我也在docker中运行了rclone。并且配置好了

但是运行如下命令时，说没找到config文件，应该是vaultwarden-backup的docker容器没办法访问rclone的docker容器，请问怎么设置？

```bash
docker run --rm -it \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  ttionya/vaultwarden-backup:latest \
  rclone config show
```

**Comment by ttionya** [comment]
@L1cardo ，

我没理解你的意思，vaultwarden-backup 的基础镜像是 rclone，不存在无法访问的情况。使用 `... rclone config` 根据命令行提示设置就可以了，确认下是不是没有完成设置生成 config 文件。

**Comment by L1cardo** [comment]
哦哦 懂了懂了，vaultwarden-backup自带rclone是吧。
你在文档说必须先配置rclone才能用vaultwarden-backup，所以我自己创建了一个rclone的容器😅😅😅
