### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by Gandulf78** [ttionya/vaultwarden-backup#52]
Hi. 
I am trying to set up Vaultwarden-backup on my NAS WDMyCloudEX2Ultra (armv7) with Vaultwarden installed but infortunately the cron task does not seem to work. 
I have no error message but there's no automatic backup. 
Here are the logs from docker logs vaultwarden_backup :

DATA_DIR: /data
DATA_DB: /data/db.sqlite3
DATA_CONFIG: /data/config.json
DATA_RSAKEY: /data/rsa_key
DATA_ATTACHMENTS: /data/attachments
DATA_SENDS: /data/sends

CRON: 5 * * * *
RCLONE_REMOTE_NAME: dropbox
RCLONE_REMOTE_DIR: /BitwardenBackup/
RCLONE_REMOTE: dropbox:/BitwardenBackup
RCLONE_GLOBAL_FLAG: 
ZIP_ENABLE: TRUE
ZIP_PASSWORD: 18 Chars
ZIP_TYPE: zip
BACKUP_FILE_DATE_FORMAT: %Y%m%d
BACKUP_KEEP_DAYS: 0
PING_URL: https://hc-ping.com/mycode 
MAIL_SMTP_ENABLE: FALSE
TIMEZONE: Europe/Paris

And here is my run command:
docker run -d \
  --restart=always \
  --name vaultwarden_backup \
  --volumes-from=vaultwarden \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  -e RCLONE_REMOTE_NAME="dropbox" \
  -e DATA_DIR="/data" \
  -e TIMEZONE=Europe/Paris \
  -e PING_URL=https://hc-ping.com/mycode \
  ttionya/vaultwarden-backup:latest

Any idea why it is not working and what I should try ?
Thank you.

**Comment by ttionya** [comment]
Hey @Gandulf78 , please check #34 , searching for issues reveals several solutions to this problem.

**Comment by Gandulf78** [comment]
> Hey @Gandulf78 , please check #34 , searching for issues reveals several solutions to this problem.

Thank you very much for this lead! I found another solution which doesn't need any update (I am not sure I can update libseccomp on my NAS) here:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

> In order to run under old Docker or libseccomp versions, the moby default seccomp profile should be downloaded and on line 2, defaultAction changed to SCMP_ACT_TRACE, then --seccomp-profile=default.json can be passed to dockerd, or --security-opt=seccomp=default.json passed to docker create or docker run. This will cause the system calls to return ENOSYS instead of EPERM, allowing the container to fall back to 32-bit time system calls. In this case, the container will not be compatible with dates past 2038.
