### ISSUE TITLE
linux/arm/v6 Docker build

### ISSUE THREAD

**Issue by Lcreager** [ttionya/vaultwarden-backup#56]
Would it be possible to build this for linux/arm/v6 and pushed to docker hub?

**Comment by ttionya** [comment]
Rclone does not provide docker images for arm/v6, and supporting it requires modifying the way docker images are built, which can take some time.

**Comment by Lcreager** [comment]
Ah, that makes sense.  I see rclone does build an armv6 binary, I will see if I can get them to push a docker image to the hub.

**Comment by ttionya** [comment]
@Lcreager ,

I tried to build an image for `arm/v6`, it's a beta version, I don't have an arm/v6 machine and I can't test it, can you please help me to make sure it works?

I'm having problems with the build process, I'm using two different Dockerfile builds, one with a special Dockerfile for arm/v6. Both builds have the same tag and the latter one overwrites the previous release, I'm trying to figure out how to fix it.

**Comment by ttionya** [comment]
Okay, I'll wait for rclone to release the `arm/v6` image and release a stable version.

**Comment by Lcreager** [comment]
I can confirm rclone and the backup script work for my webdav use case using the ttionya/vaultwarden-backup:1.11.2-beta.0 image.

So even not waiting for the arm/v6 image, your beta build did work.

**Comment by Lcreager** [comment]
When you get the chance, rclone just released and has an arm/v6 image which is now on docker hub.

**Comment by ttionya** [comment]
#68

**Comment by ttionya** [comment]
@Lcreager ,

The `ttionya/vaultwarden:latest` is now available for the `arm/v6` platform.

Please let me know if you have any questions.
