### ISSUE TITLE
Problems caused by parameter errors

### ISSUE THREAD

**Issue by Seele0oO** [ttionya/vaultwarden-backup#76]
When there are any errors in the -e parameter, the backup program is apparently normal, but it will actually get stuck and not run.
Please add the check of parameters.

**Comment by ttionya** [comment]
Based on your history title, it looks like there is an error in the `RCLONE_REMOTE_DIR` environment variable setting, but no error is reported on startup.

I would like to know what value is set that causes the error.

**Comment by Seele0oO** [comment]
I was unable to reproduce this issue as it is too old. The issue will be closed.
