### ISSUE TITLE
Error message "rclone configuration information not found"

### ISSUE THREAD

**Issue by ossie** [ttionya/vaultwarden-backup#77]
I have configured an sftp rclone target and checked with `rclone config show`. But still it restarts a few times and then exits. 
In the Docker logs (`docker logs --tail 50 --follow --timestamps vaultwarden_backup`) I have have the line: 
`... rclone configuration information not found`

**Comment by ttionya** [comment]
If the remote name you configured in rclone is not the default `BitwardenBackup`, did you specify the correct name via the environment variable `RCLONE_REMOTE_NAME`?

**Comment by ossie** [comment]
Yes, `RCLONE_REMOTE_NAME` is set the same as the rclone configuration name.

**Comment by ttionya** [comment]
I think you may not have mapped the rclone configuration file to the container correctly, please confirm.

If you can't fix it, please provide the command you executed and the environment variable configuration, only `RCLONE_REMOTE_NAME` and directory mapping configuration is needed.

```shell
# command line
--mount ?
# or
-v ?

# docker-compose.yml
environment:
  RCLONE_REMOTE_NAME: ?
volumes:
  - ?
```

**Comment by ossie** [comment]
I am sorry. It got quite obvious now, looking at shell commands again: the config volume mount had indeed the wrong path mapped.
