### ISSUE TITLE
Vaultwarden-backup disappeared completely on July 18th

### ISSUE THREAD

**Issue by queen4me** [ttionya/vaultwarden-backup#78]
I was absolutely happy having hourly backups but today I noticed that the last backup with vw-backup happened on July 18th.
The release of v1.12.2 was on July 17th. Seems not to be a coincidence though.
rclone on the host still is configured for use with OneDrive as destination.
Unfortunately I didn't save the edited docker-compose.yml and now I have to start over again.

Does somebody have any explanation how a docker container can completely disappear from the host?
Could Watchtower (another container that automatically restarts containers when a new image is available) be the reason?
Is there any chance to find the "old configuration" of the vw-backup-container on the host?

Thanks a lot for helping.
This time I'll document every step.

**Comment by queen4me** [comment]
I've just found a volume "vaultwarden-rclone-data" but that's all what's left.
Can I use this volume in a new vw-backup container?

**Comment by Kazami-Kiri** [comment]
I have not encountered this situation... 

_vaultwarden-rclone-data_ saves the rclone config file. 
If you did not change the docker environment, `volumes: - vaultwarden-rclone-data:/config/` still can be used when creating the vw-backup container, and no need to reconfigure the rclone again.

I prefer to directly bind a config file path to the container, which will be something like `volumes: - /PATH/rclone:/config/rclone`. In this case, I can backup or save the config file in other approaches, but may have other performance or security issues.

**Comment by ttionya** [comment]
I have not received similar feedback from other users.

v1.12.1 did not work on `arm/v6` and was fixed in v1.12.2. If your machine is not `arm/v6` it won't have any problems, if it is, then the backup will fail after pulling the v1.12.1 image instead of waiting until July 17.

`vaultwarden-rclone-data` you can refer to Kazami-Kiri's reply.

**Comment by queen4me** [comment]
I was able to start the container with the existing volume and now everything works like a charm again.
Thanks a lot for helping so quick!!!

**Comment by Blcktape** [comment]
I had the same issue. after the latest image pull the container is completely gone. Data is still available tough.
When recreating the image i encounter the problem that i cannot add any environment variables afterwards using portainer.

**Comment by ttionya** [comment]
@Blcktape ,

I would like to know your system and arch information. And is the `docker-compose.yml` provided by this repository being used? Did you also have the problem when upgrading from v1.12.1 to v1.12.2?

> When recreating the image i encounter the problem that i cannot add any environment variables afterwards using portainer.

I am not using docker management, can you describe the error message?

Anyway I need more information to understand what is happening.
