### ISSUE TITLE
rclone version

### ISSUE THREAD

**Issue by marklockwood-techie** [ttionya/vaultwarden-backup#81]
When configuring rclone on a headless device to use Google Drive, the auth method fails when approving the API. Google has deprecated the auth method in the packed version of rclone.

Tested manually using rclone 1.59.1 and can create a headless config on ARM6 Pi Zero

rclone config version in the docker run command shows rclone version 1.57.0-DEV

Possible issue is the ARM6 call for rclone in the Docker file;
_for linux/arm/v7 platform_
FROM rclone/rclone:1.59.1 AS image-linux-armv7
__for_ linux/arm/v6 platform_
FROM alpine:3.15 AS image-linux-armv6

**Comment by ttionya** [comment]
This is too bad, because `alpine:3.16` is missing `p7zip` in `arm/v6`, so I replaced it with another build.

But the rclone in `alpine:3.15` is only [`1.57.0`](https://pkgs.alpinelinux.org/packages?name=rclone&branch=v3.15&repo=&arch=&maintainer=), so that caused the problem.

I will try to change the build method so that `arm/v6` is also using the latest version of rclone.

**Comment by ttionya** [comment]
@marklockwood-techie ,

Hello, I fixed this issue in `1.14.3-beta.0`, please help to make sure it works properly.

**Comment by marklockwood-techie** [comment]
Thank you for your quick response. It's really appreciated.
Running the config now allows for the process to complete, however it does not seem to save the rclone,conf file

Current remotes:

docker run --rm -it   --mount type=volume,source=vaultwarden-rclone-data,target=/config/   ttionya/vaultwarden-backup:1.14.3-beta.0    rclone config

...
Name                 Type
====                 ====
BitwardenBackup      drive

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q

root@DietPi:/# docker run --rm -it   --mount type=volume,source=vaultwarden-rclone-data,target=/config/   ttionya/vaultwarden-backup:1.14.3-beta.0    rclone config show

2022/09/07 06:05:23 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
; empty config

**Comment by ttionya** [comment]
@marklockwood-techie It was my mistake, I released the fixed version `v1.14.3-beta.1`.

**Comment by marklockwood-techie** [comment]
An easy typo to make.

v1.14.3-beta.1 has allowed me to send my backups to Google Drive using the automatic backup. All is working correctly as far as I can see.

Thanks for your prompt responses.

**Comment by ttionya** [comment]
Released stable version v1.14.3.
