### ISSUE TITLE
send-mail: applet not found

### ISSUE THREAD

**Issue by hildebrau** [ttionya/vaultwarden-backup#93]
Thank you for this app.  I have it setup now; but the emails don't work.  It simply says:
send-mail: applet not found
at the end of the /app/backup.sh output. 

I feel like I'm missing some documentation or some dependency package in the container.

Thank you!

**Comment by hildebrau** [comment]
I think I figured it out.. The example docker-compose.yml file was missing the mailx parameters..  so I used something like this after signing up for a mailgun account and setting up a domain.

MAIL_SMTP_VARIABLES: '-S smtp=smtps://smtp.mailgun.org:465 -S ssl-verify=strict -r vaultwarden-backup@<removed>(Full Name Here) -S smtp-auth-user=postmaster@<removed>-S smtp-auth-password=<removed>'

**Comment by ttionya** [comment]
Yes, email notifications are not enabled in the sample docker-compose.yml. If you want to use it you need to specify environment variable `MAIL_SMTP_VARIABLES`.
