### ISSUE TITLE
使用非root用户执行的时候，似乎备份不正确？

### ISSUE THREAD

**Issue by TaoRone** [ttionya/vaultwarden-backup#96]
因为看到大大是国人，所以也就不上谷歌翻译了哈哈哈

因为使用了其他的用户去执行了命令（但是此用户被我放入了docker用户组）

按照您的[教程](https://github.com/ttionya/vaultwarden-backup/blob/master/docs/run-as-non-root-user.md)执行后，确实可以成功备份，但是本地下载解压测试，备份的内容只有raskey，而且内容为0kb……

于是我想了想，又把您教程中要求加入的--user backuptool:backuptool \删除后，备份内容正常…………

请问是我哪里误解了么……

最后，大大辛苦，很喜欢大大的项目~~

**Comment by ttionya** [comment]
抱歉过年挺忙

我本地测试正常，这种情况基本上是没有 /data 文件夹的访问权限或者里面文件的访问权限导致的。你可以提供一下异常的备份日志以及 /data 文件夹及内部文件的所有者和访问权限，这样更容易定位到问题。

**Comment by TaoRone** [comment]
> 抱歉过年挺忙
> 
> 我本地测试正常，这种情况基本上是没有 /data 文件夹的访问权限或者里面文件的访问权限导致的。你可以提供一下异常的备份日志以及 /data 文件夹及内部文件的所有者和访问权限，这样更容易定位到问题。

谢谢大大~
经测试确实是权限的问题~
重新配置权限后可以正常运行了，谢谢您~
